name: F16
description: Balanza Electrónica con Bluetooth
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  flutter_bluetooth_serial:
    path: third_party/flutter_bluetooth_serial_fork
  permission_handler: ^11.4.0
  share_plus: ^7.2.2
  excel: ^2.1.0
  path_provider: ^2.1.0
  intl: ^0.18.1
  shared_preferences: ^2.2.2  
  pdf: ^3.10.4
  printing: ^5.12.0
  device_info_plus: ^10.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

# Configuración del generador de íconos
flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/appstore.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/appstore.png"

flutter:
  uses-material-design: true
  
  assets:
    - assets/icon.png